version: '3.7'

services:

  app:
    build: 
      context: ./primegrains
      dockerfile: Dockerfile.prod        
    command: gunicorn --bind 0.0.0.0:8000 manage:app
    image: app
    container_name: app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG=0
