version: '3.7'

services:

  app:
    build: ./primegrains
    image: primegrains
    container_name: primegrains
    ports:
      - 8000:8000
    command: python primegrains/manage.py runserver -h 0.0.0.0 -p 8000

    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_CONFIG=development
      - FLASK_DEBUG=1
    env_file:
      - ./.env.dev
